### ISSUE TITLE
oneplus3 build fails with following error

### ISSUE THREAD

**Issue by isnehalkiran** [OnePlusOSS/android_hardware_qcom_bt#1]
```
     P_CB->P_CBACK(__VA_ARGS__);         \
     ^
```

system/bt/main/../btif/src/btif_av.c: In function 'btif_av_state_opened_handler':
system/bt/main/../btif/src/btif_av.c:1046:13: warning: implicit declaration of function 'btif_hf_is_call_idle' [-Wimplicit-function-declaration]
             if ((!(btif_av_cb[index].flags & BTIF_AV_FLAG_PENDING_START)) && (!btif_hf_is_call_idle())) {
             ^
system/bt/main/../btif/src/btif_av.c:1125:17: warning: implicit declaration of function 'audio_focus_status' [-Wimplicit-function-declaration]
                 audio_focus_status(BTIF_MEIDA_FOCUS_READY);
                 ^
system/bt/main/../btif/src/btif_av.c: In function 'btif_av_check_rc_connection_priority':
system/bt/main/../btif/src/btif_av.c:1985:5: warning: implicit declaration of function 'bdaddr_to_string' [-Wimplicit-function-declaration]
     BTIF_TRACE_IMP("AVCTP Address : %s ", bdaddr_to_string(&peer_bda, &addr1,
     ^
system/bt/main/../btif/src/btif_av.c: At top level:
system/bt/main/../btif/src/btif_av.c:2186:6: warning: conflicting types for 'audio_focus_status'
 void audio_focus_status(int state)
      ^
system/bt/main/../btif/src/btif_av.c:1125:17: note: previous implicit declaration of 'audio_focus_status' was here
                 audio_focus_status(BTIF_MEIDA_FOCUS_READY);
                 ^
system/bt/main/../btif/src/btif_av.c:2480:1: warning: missing initializer for field 'audio_focus_state' of 'btav_interface_t' [-Wmissing-field-initializers]
 };
 ^
In file included from system/bt/main/../btif/src/btif_av.c:35:0:
hardware/libhardware/include/hardware/bt_av.h:128:13: note: 'audio_focus_state' declared here
     void  (_audio_focus_state)( int focus_state );
             ^
target thumb C: bluetooth.default_32 <= system/bt/main/../btif/src/btif_config.c
target thumb C: bluetooth.default_32 <= system/bt/main/../btif/src/btif_core.c
system/bt/main/../btif/src/btif_core.c: In function 'btif_bredr_cleanup_event':
system/bt/main/../btif/src/btif_core.c:1113:17: error: 'BT_PROPERTY_BREDR_CLEANUP' undeclared (first use in this function)
     prop.type = BT_PROPERTY_BREDR_CLEANUP;
                 ^
system/bt/main/../btif/src/btif_core.c:1113:17: note: each undeclared identifier is reported only once for each function it appears in
system/bt/main/../btif/src/btif_core.c: In function 'btif_set_adapter_property':
system/bt/main/../btif/src/btif_core.c:1296:14: error: 'BT_PROPERTY_BREDR_CLEANUP' undeclared (first use in this function)
         case BT_PROPERTY_BREDR_CLEANUP:
              ^
make: *_\* [out/target/product/msm8996/obj_arm/SHARED_LIBRARIES/bluetooth.default_intermediates/dotdot/btif/src/btif_core.o] Error 1

**Comment by isnehalkiran** [comment]
@leonfish77101 any ideas???? how to fix that

**Comment by leonfish77101** [comment]
I think there is something wrong with your build environment. I have never upload a source code like system/bt/main/../btif/src/btif_core.c, please check your source code, and make sure the branch is oneplus3/6.0.1
If you have any questions, please ask me freely

**Comment by isnehalkiran** [comment]
ok thanks i will check that
